# Generated by Django 4.1 on 2022-08-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BundesligaResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_a", models.TextField(max_length=100)),
                ("team_b", models.TextField(max_length=100)),
                ("score_a", models.IntegerField()),
                ("score_b", models.IntegerField()),
                ("league", models.TextField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LeagueCupResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_a", models.TextField(max_length=100)),
                ("team_b", models.TextField(max_length=100)),
                ("score_a", models.IntegerField()),
                ("score_b", models.IntegerField()),
                ("league", models.TextField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ligue1Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_a", models.TextField(max_length=100)),
                ("team_b", models.TextField(max_length=100)),
                ("score_a", models.IntegerField()),
                ("score_b", models.IntegerField()),
                ("league", models.TextField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PremierLeagueResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_a", models.TextField(max_length=100)),
                ("team_b", models.TextField(max_length=100)),
                ("score_a", models.IntegerField()),
                ("score_b", models.IntegerField()),
                ("league", models.TextField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PrimeraDivisionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_a", models.TextField(max_length=100)),
                ("team_b", models.TextField(max_length=100)),
                ("score_a", models.IntegerField()),
                ("score_b", models.IntegerField()),
                ("league", models.TextField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SerieAResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_a", models.TextField(max_length=100)),
                ("team_b", models.TextField(max_length=100)),
                ("score_a", models.IntegerField()),
                ("score_b", models.IntegerField()),
                ("league", models.TextField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UefaChampsResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_a", models.TextField(max_length=100)),
                ("team_b", models.TextField(max_length=100)),
                ("score_a", models.IntegerField()),
                ("score_b", models.IntegerField()),
                ("league", models.TextField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UefaConfResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_a", models.TextField(max_length=100)),
                ("team_b", models.TextField(max_length=100)),
                ("score_a", models.IntegerField()),
                ("score_b", models.IntegerField()),
                ("league", models.TextField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UefaEuropaResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_a", models.TextField(max_length=100)),
                ("team_b", models.TextField(max_length=100)),
                ("score_a", models.IntegerField()),
                ("score_b", models.IntegerField()),
                ("league", models.TextField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UefaSuperResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_a", models.TextField(max_length=100)),
                ("team_b", models.TextField(max_length=100)),
                ("score_a", models.IntegerField()),
                ("score_b", models.IntegerField()),
                ("league", models.TextField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
