# Generated by Django 4.1 on 2022-08-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bet22PremierLeague",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_a", models.TextField(blank=True, max_length=100, null=True)),
                ("team_b", models.TextField(blank=True, max_length=100, null=True)),
                ("odd_a", models.IntegerField(blank=True, null=True)),
                ("odd_b", models.IntegerField(blank=True, null=True)),
                ("odd_c", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BetikaPremierLeague",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_a", models.TextField(blank=True, max_length=100, null=True)),
                ("team_b", models.TextField(blank=True, max_length=100, null=True)),
                ("odd_a", models.IntegerField(blank=True, null=True)),
                ("odd_b", models.IntegerField(blank=True, null=True)),
                ("odd_c", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MelBetPremierLeague",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_a", models.TextField(blank=True, max_length=100, null=True)),
                ("team_b", models.TextField(blank=True, max_length=100, null=True)),
                ("odd_a", models.IntegerField(blank=True, null=True)),
                ("odd_b", models.IntegerField(blank=True, null=True)),
                ("odd_c", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SportpesaPremierLeague",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_a", models.TextField(blank=True, max_length=100, null=True)),
                ("team_b", models.TextField(blank=True, max_length=100, null=True)),
                ("odd_a", models.IntegerField(blank=True, null=True)),
                ("odd_b", models.IntegerField(blank=True, null=True)),
                ("odd_c", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="X1betPremierLeague",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_a", models.TextField(blank=True, max_length=100, null=True)),
                ("team_b", models.TextField(blank=True, max_length=100, null=True)),
                ("odd_a", models.IntegerField(blank=True, null=True)),
                ("odd_b", models.IntegerField(blank=True, null=True)),
                ("odd_c", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
